import { Type } from 'class-transformer';
import { IsInt, IsString, Length, Max, Min } from 'class-validator';

/**
 * Parameters the website forwards from the launcher's `?desktop=1` link when asking for a
 * one-time code.
 *
 * All three originate in the LAUNCHER and travel via the browser URL, so none of them is trusted
 * beyond its shape here — the security properties come from what the values are bound to, not from
 * validation. See DesktopAuthService.
 */
export class DesktopGrantDto {
  /** Opaque CSRF/instance binding generated by the launcher. */
  @IsString()
  @Length(16, 256)
  state!: string;

  /** base64url(SHA256(verifier)). 43 chars is the length of an unpadded base64url SHA-256. */
  @IsString()
  @Length(43, 256)
  codeChallenge!: string;

  /** Loopback port the launcher is listening on. Privileged ports are rejected. */
  @Type(() => Number)
  @IsInt()
  @Min(1024)
  @Max(65535)
  port!: number;
}

/** What the launcher presents to redeem its code. */
export class DesktopExchangeDto {
  @IsString()
  @Length(16, 512)
  code!: string;

  @IsString()
  @Length(16, 256)
  state!: string;

  /** The PKCE preimage. RFC 7636 specifies 43-128 characters. */
  @IsString()
  @Length(43, 128)
  codeVerifier!: string;
}
