// Generate apps/desktop/src/ui/icons.tsx from the OFFICIAL Material Symbols SVGs.
//
// Fetches Google's own sources rather than transcribing paths by hand, so the glyphs are the real
// Material Symbols and a future refresh is a re-run instead of an eyeballing exercise.
import { writeFileSync } from 'node:fs';

// Heroicon name -> Material Symbol name. Chosen to preserve the existing meaning at each call site,
// not merely to find a similar-looking glyph.
const MAP = {
  ArrowPathIcon: 'refresh',
  ArrowUturnLeftIcon: 'undo',
  CheckCircleIcon: 'check_circle',
  CheckIcon: 'check',
  ChevronDownIcon: 'expand_more',
  ChevronUpIcon: 'expand_less',
  ClipboardDocumentIcon: 'content_paste',
  ClipboardIcon: 'content_copy',
  DocumentDuplicateIcon: 'file_copy',
  EllipsisHorizontalIcon: 'more_horiz',
  EllipsisVerticalIcon: 'more_vert',
  FunnelIcon: 'filter_alt',
  LockClosedIcon: 'lock',
  MagnifyingGlassIcon: 'search',
  PlayIcon: 'play_arrow',
  PlusIcon: 'add',
  ServerStackIcon: 'dns',
  SignalIcon: 'signal_cellular_alt',
  SparklesIcon: 'auto_awesome',
  StopIcon: 'stop',
  TrashIcon: 'delete',
  UserGroupIcon: 'group',
  XMarkIcon: 'close',
};

const BASE = 'https://raw.githubusercontent.com/google/material-design-icons/master/symbols/web';
const url = (n) => `${BASE}/${n}/materialsymbolsoutlined/${n}_24px.svg`;

const out = {};
let failed = 0;
for (const [hero, sym] of Object.entries(MAP)) {
  const res = await fetch(url(sym));
  if (!res.ok) {
    console.error(`FAIL ${sym}: HTTP ${res.status}`);
    failed++;
    continue;
  }
  const svg = await res.text();
  const d = /<path d="([^"]+)"/.exec(svg)?.[1];
  if (!d) {
    console.error(`FAIL ${sym}: no path found`);
    failed++;
    continue;
  }
  // The set is not uniform. Current-generation symbols carry viewBox="0 -960 960 960"; a few older
  // files (auto_awesome) declare only width/height="24" and use a 0..24 space. Carrying the viewBox
  // per icon renders both correctly at the same visual size, where assuming one silently squashes
  // the odd one out to a corner.
  const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1] ?? '0 0 24 24';
  out[hero] = { sym, d, viewBox };
  console.log(`ok ${hero.padEnd(24)} -> ${sym.padEnd(22)} ${String(d.length).padStart(4)} chars  ${viewBox}`);
}
if (failed) {
  console.error(`\n${failed} icon(s) failed - refusing to write a partial set`);
  process.exit(1);
}

const boxes = [...new Set(Object.values(out).map((v) => v.viewBox))];
console.log(`\nviewBoxes in use: ${boxes.join(' | ')}`);

const entries = Object.entries(out)
  .map(([hero, v]) => `  // ${v.sym}\n  ${hero}: ['${v.viewBox}', '${v.d}'],`)
  .join('\n');

const file = `// GENERATED by scripts/gen-icons.mjs - do not edit by hand.
//
// Official Material Symbols (Outlined) path data, fetched from google/material-design-icons.
//
// WHY PATHS AND NOT THE FONT. The Material Symbols variable woff2 is 312.7 KB for ~3,600 glyphs -
// larger than this app's entire JavaScript bundle (237 KB) - and we draw ${Object.keys(out).length}. Inlining the paths
// costs about 6 KB, tree-shakes, renders crisply at any size, and avoids the icon-shaped flash a
// webfont produces before it loads. Same glyphs, same source, same licence (Apache-2.0).
//
// To add an icon: add a Heroicon-style name -> Material Symbol name pair in scripts/gen-icons.mjs
// and re-run it. Do not paste path data in by hand.

// [viewBox, path]. The viewBox is per icon because the upstream set is not uniform.
export const ICON_PATHS = {
${entries}
} as const;

export type IconName = keyof typeof ICON_PATHS;
`;

writeFileSync(process.argv[2], file, 'utf8');
console.log(`wrote ${process.argv[2]} (${Object.keys(out).length} icons)`);
