#!/usr/bin/env node
/**
 * Vendor the Google Sans web font into apps/desktop/src/assets/fonts.
 *
 *   node scripts/vendor-fonts.mjs
 *
 * SELF-HOSTED, NOT A CDN LINK. A launcher that fetches fonts.googleapis.com on every start makes a
 * third-party request before the user has done anything, breaks entirely offline, and is a poor look
 * for an anti-detect product. The files are ~20 KB; there is no upside to fetching them.
 *
 * LATIN SUBSETS ONLY. Google Sans ships 25 subsets totalling 942 KB. The launcher UI is Latin-script,
 * so latin + latin-ext cover it at a fraction of that. Profile *content* is rendered by the Lobium
 * engine with its own fonts and is unaffected by this choice.
 *
 * Licence: Google Sans is in the public Google Fonts catalog (isOpenSource=true). Note that Product
 * Sans is NOT - it is served with a `license/googlerestricted` banner and is absent from the
 * catalog. Do not substitute one for the other.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'apps', 'desktop', 'src', 'assets', 'fonts');

// A modern browser UA is required: the CSS2 API serves woff2 only to clients it believes support it,
// and falls back to much larger ttf otherwise.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Safari/537.36';

const WANT = new Set(['latin', 'latin-ext']);
const FAMILY = 'Google Sans';
const CSS_URL = 'https://fonts.googleapis.com/css2?family=Google+Sans:wght@400..700&display=swap';

const css = await fetch(CSS_URL, { headers: { 'User-Agent': UA } }).then((r) => {
  if (!r.ok) throw new Error(`font CSS: HTTP ${r.status}`);
  return r.text();
});

// Each @font-face is preceded by a `/* subset */` comment naming the subset it covers.
const blocks = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]+\})/g)];
if (!blocks.length) throw new Error('could not parse any @font-face blocks from the Google Fonts CSS');

await mkdir(OUT, { recursive: true });

const faces = [];
for (const [, subset, block] of blocks) {
  if (!WANT.has(subset)) continue;
  const url = /url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/.exec(block)?.[1];
  const unicodeRange = /unicode-range:\s*([^;]+);/.exec(block)?.[1]?.trim();
  const weight = /font-weight:\s*([^;]+);/.exec(block)?.[1]?.trim() ?? '400';
  if (!url) continue;

  const bytes = Buffer.from(await fetch(url, { headers: { 'User-Agent': UA } }).then((r) => r.arrayBuffer()));
  const file = `google-sans-${subset}.woff2`;
  await writeFile(join(OUT, file), bytes);
  faces.push({ subset, file, weight, unicodeRange, kb: (bytes.length / 1024).toFixed(1) });
  console.log(`  ${file.padEnd(30)} ${String(bytes.length).padStart(7)} bytes  weight ${weight}`);
}

if (!faces.length) throw new Error(`no ${[...WANT].join('/')} subset found in the CSS`);

// Vite fingerprints and inlines these via the ?url import in the generated CSS, so the paths here are
// relative to this file and resolved at build time rather than at runtime.
const out = `/* GENERATED by scripts/vendor-fonts.mjs - do not edit by hand.
 *
 * ${FAMILY}, self-hosted. Latin subsets only (the full family is 25 subsets / 942 KB).
 * Re-run the script to refresh; do not hand-edit the unicode-range values, they come from Google.
 */
${faces
  .map(
    (f) => `@font-face {
  font-family: '${FAMILY}';
  font-style: normal;
  font-weight: ${f.weight};
  font-display: swap;
  src: url('./fonts/${f.file}') format('woff2');
  unicode-range: ${f.unicodeRange};
}`,
  )
  .join('\n')}
`;

await writeFile(join(ROOT, 'apps', 'desktop', 'src', 'assets', 'google-sans.css'), out, 'utf8');
const total = faces.reduce((n, f) => n + Number(f.kb), 0);
console.log(`\nwrote ${faces.length} face(s), ${total.toFixed(1)} KB total, + assets/google-sans.css`);
