import { pagerItems } from './pager';

/**
 * Classic numbered pagination — ‹ 1 2 … 9 › — shared by every table that pages (Profiles, Proxies,
 * Templates), so the three lists cannot drift into three paging dialects.
 *
 * Renders NOTHING when there is one page: a pager on an unpaged list is a control that answers a
 * question nobody asked. The arrows are text glyphs rather than icons because `icons.tsx` is
 * generated by scripts/gen-icons.mjs (outside this tree) and ‹ › at this size read identically.
 *
 * The component trusts `page` to be already clamped by the caller (see `clampPage` in pager.ts) —
 * the caller owns the page state and has to clamp it anyway to slice the right rows.
 */
export function Pager({
  page,
  pageCount,
  onPageChange,
  label = 'Pagination',
}: {
  /** Current 1-based page, already clamped to [1, pageCount]. */
  page: number;
  pageCount: number;
  onPageChange: (page: number) => void;
  /** Accessible name; name the list when a view holds more than one. */
  label?: string;
}): JSX.Element | null {
  if (pageCount <= 1) return null;
  return (
    <nav className="lb-pager" aria-label={label}>
      <button
        type="button"
        className="lb-pager__arrow"
        disabled={page <= 1}
        aria-label="Previous page"
        onClick={() => onPageChange(page - 1)}
      >
        ‹
      </button>
      {pagerItems(page, pageCount).map((item, index) =>
        item === 'gap' ? (
          // The index is a stable enough key here: gaps only ever appear around the current page,
          // and the whole strip re-renders when the page changes anyway.
          <span key={`gap-${index}`} className="lb-pager__gap" aria-hidden>
            …
          </span>
        ) : (
          <button
            key={item}
            type="button"
            className={item === page ? 'lb-pager__page lb-pager__page--current' : 'lb-pager__page'}
            aria-current={item === page ? 'page' : undefined}
            aria-label={`Page ${item}`}
            onClick={() => onPageChange(item)}
          >
            {item}
          </button>
        ),
      )}
      <button
        type="button"
        className="lb-pager__arrow"
        disabled={page >= pageCount}
        aria-label="Next page"
        onClick={() => onPageChange(page + 1)}
      >
        ›
      </button>
    </nav>
  );
}
